apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javawebapprs2
  namespace: makutaworld
spec:
  replicas: 3
  selector:
    matchLabels:
     app: javawebapptwo
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapptwo
    spec:
      containers:
      - name: javawebappcontainer2
        image: agunuworld/java-web-app:22
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: javawebapppodsvc2
  namespace: makutaworld
spec:
  type: NodePort
  selector:
    app: javawebapptwo
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30005

