apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mavenwebapprs
  namespace: makutaworld
spec:
  replicas: 3
  selector:
    matchLabels:
     app: mavenwebappone
  template:
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebappone
    spec:
      containers:
      - name: mavenwebappcontainer
        image: agunuworld/java-web-app:8
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebapppodsvc
  namespace: makutaworld
spec:
  type: LoadBalancer
  selector:
    app: mavenwebappone
  ports:
  - port: 80
    targetPort: 8080

