#Endpoint controllers joins services and pods together
#kubectl describe svc or pod -n namespace
apiVersion: v1
kind: Pod
metadata:
  name: podkindcontroller
  namespace: podkindward4
  labels:
    app: javawebapppodkind
spec:
  containers:
  - name: javawebapppodkindcontainer
    image: agunuworld/java-web-app:22
    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: javawebapppodsvc
  namespace: podkindward4
spec:
  type: NodePort
  selector:
    app: javawebapppodkind
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
