apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: springapprs
  namespace: agunuworld7
spec:
  replicas: 3
  selector:
    matchLabels:
     app: springappls
  template:
    metadata:
      name: springapppod
      labels:
        app: springappls
    spec:
      containers:
      - name: springappcontainer
        image: agunuworld/spring-boot-mongo
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springapppodsvc
  namespace: agunuworld7
spec:
  type: NodePort
  selector:
    app: springappls
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30004

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongoapprs
  namespace: agunuworld7
spec:
  selector:
    matchLabels:
     app: mongo
  template:
    metadata:
      name: mongogapppod
      labels:
        app: mongo
    spec:
      volumes:
      - name: mongonfshostpath
        persistentVolumeClaim:
           claimName: pvc-nfs-pv1            #/tmp/mongobkp or /opt/mybkp
      containers:
      - name: mongocontainer
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongonfshostpath
          mountPath: /data/db
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: agunuworld7
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017

