apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv1
  namespace: agunuworld7
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 35.235.103.123
    path: "/agunubackup/agunubackup4/"




