apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv1
  namespace: agunuworld4
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.8.183
    path: "/nfsbackup/backupfolder"
