---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: agunuworld2
  labels:
    app: wordpress
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
        - image: mysql:5.7
          imagePullPolicy: Always
          name: mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
               configMapKeyRef:
                  name: mysql-configmap
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        hostPath:
          path: /tmp/mysqlbackup

---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: agunuworld2
spec:
  selector:
    app: wordpress
    tier: mysql
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 3306
    protocol: TCP
