apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springboot
  name: spring-controller
  namespace: agunuworld4
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: dockerhandson/spring-boot-mongo:latest
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080       
---
# Load Balancer Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot
  name: springboot
  namespace: agunuworld4
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: springboot

---
# Mongo host path rc
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
  namespace: agunuworld4
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      volumes:
      - name: pvc-nfs-pv1
        persistentVolumeClaim:
          claimName: pvc-nfs-pv1      
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: pvc-nfs-pv1
          mountPath: /data/db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-pv1
  namespace: agunuworld4
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi

---
# Mongo Node Port RC
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
  namespace: agunuworld4
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
...
